databases:
  - name: wordlejj
    databaseName: wordlejj
    user: wordlejj
    plan: starter

services:
  - type: web
    name: wordlejj-fe
    env: static
    plan: starter
    rootDir: ./frontend
    buildCommand: npm i; npm run build
    staticPublishPath: out
    autoDeploy: false
    envVars:
    - key: NODE_ENV
      value: production
  - type: web
    name: wordlejj-be
    env: python
    plan: free
    rootDir: ./backend
    buildCommand: "./backend/build.sh"
    startCommand: "gunicorn wjj.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wordlejj
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
