import Head from 'next/head'
import { Game } from '@/components/Game/Game'
import GameProvider from '@/providers/GameProvider/GameProvider'
import { ThemeProvider } from 'styled-components'
import { theme } from '@/theme'
import { ModalProvider } from 'styled-react-modal'
import Script from 'next/script'

export default function Index() {
  return (
    <>
      <Head>
        <title>WORDLE JITSU</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script src="https://www.googletagmanager.com/gtag/js?id=G-735GV7C6W8" />
      <Script id="google-analytics">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-735GV7C6W8');
        `}
      </Script>
      <Script id="google-tag-manager" strategy="afterInteractive">
      {`
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','GTM-5MM6RDT');
      `}
      </Script>
      <noscript>
        <iframe
          src={`https://www.googletagmanager.com/ns.html?id=GTM-5MM6RDT`}
          height="0"
          width="0"
          style={{ display: "none", visibility: "hidden" }}
        />
      </noscript>

      <ThemeProvider theme={theme}>
        <ModalProvider>
          <GameProvider>
            <Game />
          </GameProvider>
        </ModalProvider>
      </ThemeProvider>
    </>
  )
}
